defaultChannel: g

helpMessage: 
    a: .&7----------&c[&aBDchat&c]&7----------
    b: .&cAuthor - &7StevenMG and Addicted_24_7
    c: .&cVersion - &73.1
    d: .&7Look us up on BukkitDev! dev.bukkit.org/server-mods/bdchat/
    e: .&7Change channels using /cc (Channel Name)
    f: .&7For a list of channels do /BDchat list